language: java
jdk:
  - openjdk8
script: xvfb-run mvn verify -B -Pjacoco

# Cache maven repository to speed up build
cache:
   directories:
      - $HOME/.m2

# Before the build, install R with required packages
before_install:
# Install R 3.2 instead of R 3.0 from base Ubuntu
- sudo sh -c 'echo "deb http://cran.rstudio.com/bin/linux/ubuntu trusty/" >> /etc/apt/sources.list'
- gpg --keyserver keyserver.ubuntu.com --recv-key E084DAB9
- gpg -a --export E084DAB9 | sudo apt-key add -
- sudo apt-get update -qq > /dev/null
- sudo apt-get --allow-unauthenticated install r-base -qq > /dev/null
# Install packages
- sudo apt-get install libcurl4-openssl-dev libxml2-dev libssl-dev -qq > /dev/null
- sudo R --vanilla -e 'install.packages(c("Rserve", "miniCRAN", "ggplot2", "svglite"), dependencies=TRUE, repos="http://cran.us.r-project.org", Ncpus=1)' > /dev/null

# If build succeeds upload test coverage report
after_success:
- pushd $TRAVIS_BUILD_DIR/de.bund.bfr.knime.testreport/target/site/jacoco-aggregate
- bash <(curl -s https://codecov.io/bash)
- popd

# Integration test. Try to install build on KNIME.
before_deploy:
- wget -q http://download.knime.org/analytics-platform/linux/knime_3.7.1.linux.gtk.x86_64.tar.gz
- tar -xzf knime_3.7.1.linux.gtk.x86_64.tar.gz
- rm knime_3.7.1.linux.gtk.x86_64.tar.gz
- KNIME_REPO="https://update.knime.org/analytics-platform/3.7"
- LOCAL_REPO="file://$TRAVIS_BUILD_DIR/releng/de.bund.bfr.knime.update/target/repository"
- REMOTE_REPO="https://dl.bintray.com/silebat/fsklab_icpmf"
# Install FSK-Lab from update site (old build)
- knime_3.7.1/knime -application org.eclipse.equinox.p2.director -repository $KNIME_REPO,$REMOTE_REPO -installIU de.bund.bfr.knime.fsklab.feature.feature.group
# Uninstall FSK-Lab and update with new local build
- knime_3.7.1/knime -application org.eclipse.equinox.p2.director -uninstallIU de.bund.bfr.knime.fsklab.feature.feature.group
- knime_3.7.1/knime -application org.eclipse.equinox.p2.director -repository $KNIME_REPO,$LOCAL_REPO -installIU de.bund.bfr.knime.fsklab.feature.feature.group
- rm -Rf knime_3.7.1

# Deploy build
deploy:
- provider: script
  skip_cleanup: true # to upload artifacts created during the build
  script: bash bintray.sh
  on: test
