
language: java
dist: Xenial
jdk:
  - openjdk8
script:
- xvfb-run mvn verify -B -Pjacoco


# Cache maven repository to speed up build
cache:
   directories:
      - $HOME/.m2

# Before the build, install R with required packages
before_install:
# Install R 3.2 instead of R 3.0 from base Ubuntu
- sudo sh -c 'echo "deb http://cran.rstudio.com/bin/linux/ubuntu trusty/" >> /etc/apt/sources.list'
- sudo apt-get --allow-unauthenticated update -qq
- sudo apt-get --allow-unauthenticated install r-base -qq
# Install packages
- sudo apt-get install libcurl4-openssl-dev libxml2-dev libssl-dev -qq
- sudo R --vanilla -e 'install.packages(c("Rserve", "miniCRAN", "ggplot2", "svglite"), repos="https://cran.rstudio.com", Ncpus=2)'


# If build succeeds upload test coverage report
after_success:
- pushd $TRAVIS_BUILD_DIR/de.bund.bfr.knime.testreport/target/site/jacoco-aggregate
- bash <(curl -s https://codecov.io/bash)
- popd

# Deploy build
deploy:
- provider: script
  skip_cleanup: true # to upload artifacts created during the build
  script: bash gitlab.sh
  on:
    branch: release
- provider: script
  skip_cleanup: true # to upload artifacts created during the build
  script: bash gitlab_development.sh
  on:
    branch: development
