language: java
dist: trusty
jdk:
  - openjdk8
script:
- xvfb-run mvn verify -B -Pjacoco

- FOLDER="$TRAVIS_BUILD_DIR/de.bund.bfr.knime.update/target/repository"
- KNIME_FILE="knime_3.7.2.linux.gtk.x86_64.tar.gz"
- wget -v "http://download.knime.org/analytics-platform/linux/$KNIME_FILE"
- tar -xzf $KNIME_FILE
- rm $KNIME_FILE

- KNIME37="https://update.knime.org/analytics-platform/3.7"

- OLD_FSK="https://dl.bintray.com/silebat/fsklab_test"
- NEW_FSK="file:$TRAVIS_BUILD_DIR/de.bund.bfr.knime.update/target/repository"

- WF="https://dl.bintray.com/schuelet-test/test_wf"
- WF_NAME="fsk_lab_test_wf.knwf"

- KNIME_SUCCESS="Workflow executed sucessfully"


- echo "================== TESTING THE FRESH INSTALL OF FSK-LAB of KNIME 3.7.2 ==============================================================="

- echo "INSTALL NEW FSK-LAB INTO FRESH KNIME"
- knime_3.7.2/knime -application org.eclipse.equinox.p2.director -repository "$KNIME37,$NEW_FSK" -installIU de.bund.bfr.knime.fsklab.feature.feature.group,org.knime.features.testingapplication.feature.group
- knime_3.7.2/knime -application org.eclipse.equinox.p2.director -lir
- wget -v "$WF/$WF_NAME"
- KNIME_OUT=$(knime_3.7.2/knime -nosplash -application org.knime.product.KNIME_BATCH_APPLICATION -workflowFile="$WF_NAME" --launcher.suppressErrors)
- if [[ "$KNIME_OUT" != *"$KNIME_SUCCESS"* ]]; then  echo "Workflow failed";exit 1; else echo "3.7.2 WORKFLOW SUCCESSFUL ON FRESH INSTALL"; fi
- rm $WF_NAME
- echo "REMOVE NEW FSK TO TEST UPDATE FROM OLDER VERSION"
- knime_3.7.2/knime -application org.eclipse.equinox.p2.director -uninstallIU de.bund.bfr.knime.fsklab.feature.feature.group
- knime_3.7.2/knime -application org.eclipse.equinox.p2.director -lir


- echo "================== TESTING THE UPDATE FROM OLD FSK-LAB ==============================================================================="

- echo "INSTALL OLD FSK-LAB TEMPORARILY"
- knime_3.7.2/knime -application org.eclipse.equinox.p2.director -repository "$KNIME37,$OLD_FSK" -installIU de.bund.bfr.knime.fsklab.feature.feature.group
- knime_3.7.2/knime -application org.eclipse.equinox.p2.director -lir
- echo "REMOVING OLD FSK-LAB"
- knime_3.7.2/knime -application org.eclipse.equinox.p2.director -uninstallIU de.bund.bfr.knime.fsklab.feature.feature.group
- knime_3.7.2/knime -application org.eclipse.equinox.p2.director -lir
- echo "REINSTALLING NEW FSK-LAB"
- knime_3.7.2/knime -application org.eclipse.equinox.p2.director -repository "$KNIME37,$NEW_FSK" -installIU de.bund.bfr.knime.fsklab.feature.feature.group
- knime_3.7.2/knime -application org.eclipse.equinox.p2.director -lir
- wget -v "$WF/$WF_NAME"
- KNIME_OUT=$(knime_3.7.2/knime -nosplash -application org.knime.product.KNIME_BATCH_APPLICATION -workflowFile="$WF_NAME" --launcher.suppressErrors)
- if [[ "$KNIME_OUT" != *"$KNIME_SUCCESS"* ]]; then  echo "Workflow failed";exit 1; else echo "3.7.2 WORKFLOW SUCCESSFUL ON UPDATE"; fi
- rm $WF_NAME

- echo "CLEANING KNIME"
- rm -Rf knime_3.7.2

# -------------------------------------------DO THE SAME FOR KNIME 4.1.2 -------------------------------------------------------------------

- KNIME_FILE="knime_4.1.2.linux.gtk.x86_64.tar.gz"
- wget -v "http://download.knime.org/analytics-platform/linux/$KNIME_FILE"
- tar -xzf $KNIME_FILE
- rm $KNIME_FILE
- KNIME41="https://update.knime.com/analytics-platform/4.1"


- echo "================== TESTING THE FRESH INSTALL OF FSK-LAB of KNIME 4.1.2 ==============================================================="

- echo "INSTALL NEW FSK-LAB INTO FRESH KNIME"
- knime_4.1.2/knime -application org.eclipse.equinox.p2.director -repository "$KNIME41,$NEW_FSK" -installIU de.bund.bfr.knime.fsklab.feature.feature.group,org.knime.features.testing.application.feature.group
- knime_4.1.2/knime -application org.eclipse.equinox.p2.director -lir
- wget -v "$WF/$WF_NAME"
- knime_4.1.2/knime -nosplash -application org.knime.product.KNIME_BATCH_APPLICATION -workflowFile="$WF_NAME"
- KNIME_OUT=$(knime_4.1.2/knime -nosplash -application org.knime.product.KNIME_BATCH_APPLICATION -workflowFile="$WF_NAME" --launcher.suppressErrors)
- if [[ "$KNIME_OUT" != *"$KNIME_SUCCESS"* ]]; then  echo "Workflow failed";exit 1; else echo "4.1.2 WORKFLOW SUCCESSFUL ON FRESH INSTALL"; fi
- rm $WF_NAME
- echo "REMOVE NEW FSK TO TEST UPDATE FROM OLDER VERSION"
- knime_4.1.2/knime -application org.eclipse.equinox.p2.director -uninstallIU de.bund.bfr.knime.fsklab.feature.feature.group
- knime_4.1.2/knime -application org.eclipse.equinox.p2.director -lir


- echo "================== TESTING THE UPDATE FROM OLD FSK-LAB ==============================================================================="

- echo "INSTALL OLD FSK-LAB TEMPORARILY"
- knime_4.1.2/knime -application org.eclipse.equinox.p2.director -repository "$KNIME41,$OLD_FSK" -installIU de.bund.bfr.knime.fsklab.feature.feature.group
- knime_4.1.2/knime -application org.eclipse.equinox.p2.director -lir
- echo "REMOVING OLD FSK-LAB"
- knime_4.1.2/knime -application org.eclipse.equinox.p2.director -uninstallIU de.bund.bfr.knime.fsklab.feature.feature.group
- knime_4.1.2/knime -application org.eclipse.equinox.p2.director -lir
- echo "REINSTALLING NEW FSK-LAB"
- knime_4.1.2/knime -application org.eclipse.equinox.p2.director -repository "$KNIME41,$NEW_FSK" -installIU de.bund.bfr.knime.fsklab.feature.feature.group
- knime_4.1.2/knime -application org.eclipse.equinox.p2.director -lir
- wget -v "$WF/$WF_NAME"
- KNIME_OUT=$(knime_4.1.2/knime -nosplash -application org.knime.product.KNIME_BATCH_APPLICATION -workflowFile="$WF_NAME" --launcher.suppressErrors)
- if [[ "$KNIME_OUT" != *"$KNIME_SUCCESS"* ]]; then  echo "Workflow failed";exit 1; else echo "4.1.2 WORKFLOW SUCCESSFUL ON UPDATE"; fi
- rm $WF_NAME

- echo "CLEANING KNIME"
- rm -Rf knime_4.1.2





# Cache maven repository to speed up build
cache:
   directories:
      - $HOME/.m2

# Before the build, install R with required packages
before_install:
# Install R 3.2 instead of R 3.0 from base Ubuntu
- sudo sh -c 'echo "deb http://cran.rstudio.com/bin/linux/ubuntu trusty/" >> /etc/apt/sources.list'
- sudo apt-get --allow-unauthenticated update -qq
- sudo apt-get --allow-unauthenticated install r-base -qq
# Install packages
- sudo apt-get install libcurl4-openssl-dev libxml2-dev libssl-dev -qq
- sudo R --vanilla -e 'install.packages(c("Rserve", "miniCRAN", "ggplot2", "svglite"), repos="https://cran.rstudio.com", Ncpus=2)'


# If build succeeds upload test coverage report
after_success:
- pushd $TRAVIS_BUILD_DIR/de.bund.bfr.knime.testreport/target/site/jacoco-aggregate
- bash <(curl -s https://codecov.io/bash)
- popd

# Deploy build
deploy:
- provider: script
  skip_cleanup: true # to upload artifacts created during the build
  script: bash bintray.sh
  on: test