language: java
script: mvn clean verify
# Cache maven repository to speed up build
cache:
   directories:
      - $HOME/.m2
notifications:
   # Email notifications are disabled
   email: false
deploy:
-  provider: script
   skip_cleanup: true # to upload artifacts created during the build
   script: bash bintray.sh
   on:
      branch: release
-  provider: script
   skip_cleanup: true
   script: bash bintray_nightly.sh
   on:
      branch: master
      condition: $TRAVIS_EVENT_TYPE = cron
