/*
 * RAKIP Generic model
 * TODO
 *
 * OpenAPI spec version: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.bund.bfr.metadata.swagger;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * QualityMeasures
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-07-02T16:22:48.194+02:00")
public class QualityMeasures {
  @SerializedName("SSE")
  private BigDecimal SSE = null;

  @SerializedName("MSE")
  private BigDecimal MSE = null;

  @SerializedName("RMSE")
  private BigDecimal RMSE = null;

  @SerializedName("RSquared")
  private BigDecimal rsquared = null;

  @SerializedName("AIC")
  private BigDecimal AIC = null;

  @SerializedName("BIC")
  private BigDecimal BIC = null;

  public QualityMeasures SSE(BigDecimal SSE) {
    this.SSE = SSE;
    return this;
  }

   /**
   * Statistical values calculated to describe the performance of the model fitting procedure
   * @return SSE
  **/
  @ApiModelProperty(value = "Statistical values calculated to describe the performance of the model fitting procedure")
  public BigDecimal getSSE() {
    return SSE;
  }

  public void setSSE(BigDecimal SSE) {
    this.SSE = SSE;
  }

  public QualityMeasures MSE(BigDecimal MSE) {
    this.MSE = MSE;
    return this;
  }

   /**
   * Statistical values calculated to describe the performance of the model fitting procedure
   * @return MSE
  **/
  @ApiModelProperty(value = "Statistical values calculated to describe the performance of the model fitting procedure")
  public BigDecimal getMSE() {
    return MSE;
  }

  public void setMSE(BigDecimal MSE) {
    this.MSE = MSE;
  }

  public QualityMeasures RMSE(BigDecimal RMSE) {
    this.RMSE = RMSE;
    return this;
  }

   /**
   * Statistical values calculated to describe the performance of the model fitting procedure
   * @return RMSE
  **/
  @ApiModelProperty(value = "Statistical values calculated to describe the performance of the model fitting procedure")
  public BigDecimal getRMSE() {
    return RMSE;
  }

  public void setRMSE(BigDecimal RMSE) {
    this.RMSE = RMSE;
  }

  public QualityMeasures rsquared(BigDecimal rsquared) {
    this.rsquared = rsquared;
    return this;
  }

   /**
   * Statistical values calculated to describe the performance of the model fitting procedure
   * @return rsquared
  **/
  @ApiModelProperty(value = "Statistical values calculated to describe the performance of the model fitting procedure")
  public BigDecimal getRsquared() {
    return rsquared;
  }

  public void setRsquared(BigDecimal rsquared) {
    this.rsquared = rsquared;
  }

  public QualityMeasures AIC(BigDecimal AIC) {
    this.AIC = AIC;
    return this;
  }

   /**
   * Statistical values calculated to describe the performance of the model fitting procedure
   * @return AIC
  **/
  @ApiModelProperty(value = "Statistical values calculated to describe the performance of the model fitting procedure")
  public BigDecimal getAIC() {
    return AIC;
  }

  public void setAIC(BigDecimal AIC) {
    this.AIC = AIC;
  }

  public QualityMeasures BIC(BigDecimal BIC) {
    this.BIC = BIC;
    return this;
  }

   /**
   * Statistical values calculated to describe the performance of the model fitting procedure
   * @return BIC
  **/
  @ApiModelProperty(value = "Statistical values calculated to describe the performance of the model fitting procedure")
  public BigDecimal getBIC() {
    return BIC;
  }

  public void setBIC(BigDecimal BIC) {
    this.BIC = BIC;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QualityMeasures qualityMeasures = (QualityMeasures) o;
    return Objects.equals(this.SSE, qualityMeasures.SSE) &&
        Objects.equals(this.MSE, qualityMeasures.MSE) &&
        Objects.equals(this.RMSE, qualityMeasures.RMSE) &&
        Objects.equals(this.rsquared, qualityMeasures.rsquared) &&
        Objects.equals(this.AIC, qualityMeasures.AIC) &&
        Objects.equals(this.BIC, qualityMeasures.BIC);
  }

  @Override
  public int hashCode() {
    return Objects.hash(SSE, MSE, RMSE, rsquared, AIC, BIC);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QualityMeasures {\n");
    
    sb.append("    SSE: ").append(toIndentedString(SSE)).append("\n");
    sb.append("    MSE: ").append(toIndentedString(MSE)).append("\n");
    sb.append("    RMSE: ").append(toIndentedString(RMSE)).append("\n");
    sb.append("    rsquared: ").append(toIndentedString(rsquared)).append("\n");
    sb.append("    AIC: ").append(toIndentedString(AIC)).append("\n");
    sb.append("    BIC: ").append(toIndentedString(BIC)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

