/*
 * RAKIP Generic model
 * TODO
 *
 * OpenAPI spec version: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.bund.bfr.metadata.swagger;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Study
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-07-02T16:22:48.194+02:00")
public class Study {
  @SerializedName("identifier")
  private String identifier = null;

  @SerializedName("title")
  private String title = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("designType")
  private String designType = null;

  @SerializedName("assayMeasurementType")
  private String assayMeasurementType = null;

  @SerializedName("assayTechnologyType")
  private String assayTechnologyType = null;

  @SerializedName("assayTechnologyPlatform")
  private String assayTechnologyPlatform = null;

  @SerializedName("accreditationProcedureForTheAssayTechnology")
  private String accreditationProcedureForTheAssayTechnology = null;

  @SerializedName("protocolName")
  private String protocolName = null;

  @SerializedName("protocolType")
  private String protocolType = null;

  @SerializedName("protocolDescription")
  private String protocolDescription = null;

  @SerializedName("protocolURI")
  private String protocolURI = null;

  @SerializedName("protocolVersion")
  private String protocolVersion = null;

  @SerializedName("protocolParametersName")
  private String protocolParametersName = null;

  @SerializedName("protocolComponentsName")
  private String protocolComponentsName = null;

  @SerializedName("protocolComponentsType")
  private String protocolComponentsType = null;

  public Study identifier(String identifier) {
    this.identifier = identifier;
    return this;
  }

   /**
   * A user defined identifier for the study
   * @return identifier
  **/
  @ApiModelProperty(value = "A user defined identifier for the study")
  public String getIdentifier() {
    return identifier;
  }

  public void setIdentifier(String identifier) {
    this.identifier = identifier;
  }

  public Study title(String title) {
    this.title = title;
    return this;
  }

   /**
   * A title for the Study
   * @return title
  **/
  @ApiModelProperty(required = true, value = "A title for the Study")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public Study description(String description) {
    this.description = description;
    return this;
  }

   /**
   * A brief description of the study aims
   * @return description
  **/
  @ApiModelProperty(value = "A brief description of the study aims")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Study designType(String designType) {
    this.designType = designType;
    return this;
  }

   /**
   * The type of study design being employed
   * @return designType
  **/
  @ApiModelProperty(value = "The type of study design being employed")
  public String getDesignType() {
    return designType;
  }

  public void setDesignType(String designType) {
    this.designType = designType;
  }

  public Study assayMeasurementType(String assayMeasurementType) {
    this.assayMeasurementType = assayMeasurementType;
    return this;
  }

   /**
   * The measurement being observed in this assay
   * @return assayMeasurementType
  **/
  @ApiModelProperty(value = "The measurement being observed in this assay")
  public String getAssayMeasurementType() {
    return assayMeasurementType;
  }

  public void setAssayMeasurementType(String assayMeasurementType) {
    this.assayMeasurementType = assayMeasurementType;
  }

  public Study assayTechnologyType(String assayTechnologyType) {
    this.assayTechnologyType = assayTechnologyType;
    return this;
  }

   /**
   * The technology being employed to observe this measurement
   * @return assayTechnologyType
  **/
  @ApiModelProperty(value = "The technology being employed to observe this measurement")
  public String getAssayTechnologyType() {
    return assayTechnologyType;
  }

  public void setAssayTechnologyType(String assayTechnologyType) {
    this.assayTechnologyType = assayTechnologyType;
  }

  public Study assayTechnologyPlatform(String assayTechnologyPlatform) {
    this.assayTechnologyPlatform = assayTechnologyPlatform;
    return this;
  }

   /**
   * The technology platform used
   * @return assayTechnologyPlatform
  **/
  @ApiModelProperty(value = "The technology platform used")
  public String getAssayTechnologyPlatform() {
    return assayTechnologyPlatform;
  }

  public void setAssayTechnologyPlatform(String assayTechnologyPlatform) {
    this.assayTechnologyPlatform = assayTechnologyPlatform;
  }

  public Study accreditationProcedureForTheAssayTechnology(String accreditationProcedureForTheAssayTechnology) {
    this.accreditationProcedureForTheAssayTechnology = accreditationProcedureForTheAssayTechnology;
    return this;
  }

   /**
   * Description
   * @return accreditationProcedureForTheAssayTechnology
  **/
  @ApiModelProperty(value = "Description")
  public String getAccreditationProcedureForTheAssayTechnology() {
    return accreditationProcedureForTheAssayTechnology;
  }

  public void setAccreditationProcedureForTheAssayTechnology(String accreditationProcedureForTheAssayTechnology) {
    this.accreditationProcedureForTheAssayTechnology = accreditationProcedureForTheAssayTechnology;
  }

  public Study protocolName(String protocolName) {
    this.protocolName = protocolName;
    return this;
  }

   /**
   * Description
   * @return protocolName
  **/
  @ApiModelProperty(value = "Description")
  public String getProtocolName() {
    return protocolName;
  }

  public void setProtocolName(String protocolName) {
    this.protocolName = protocolName;
  }

  public Study protocolType(String protocolType) {
    this.protocolType = protocolType;
    return this;
  }

   /**
   * Description
   * @return protocolType
  **/
  @ApiModelProperty(value = "Description")
  public String getProtocolType() {
    return protocolType;
  }

  public void setProtocolType(String protocolType) {
    this.protocolType = protocolType;
  }

  public Study protocolDescription(String protocolDescription) {
    this.protocolDescription = protocolDescription;
    return this;
  }

   /**
   * Description
   * @return protocolDescription
  **/
  @ApiModelProperty(value = "Description")
  public String getProtocolDescription() {
    return protocolDescription;
  }

  public void setProtocolDescription(String protocolDescription) {
    this.protocolDescription = protocolDescription;
  }

  public Study protocolURI(String protocolURI) {
    this.protocolURI = protocolURI;
    return this;
  }

   /**
   * Description
   * @return protocolURI
  **/
  @ApiModelProperty(value = "Description")
  public String getProtocolURI() {
    return protocolURI;
  }

  public void setProtocolURI(String protocolURI) {
    this.protocolURI = protocolURI;
  }

  public Study protocolVersion(String protocolVersion) {
    this.protocolVersion = protocolVersion;
    return this;
  }

   /**
   * Description
   * @return protocolVersion
  **/
  @ApiModelProperty(value = "Description")
  public String getProtocolVersion() {
    return protocolVersion;
  }

  public void setProtocolVersion(String protocolVersion) {
    this.protocolVersion = protocolVersion;
  }

  public Study protocolParametersName(String protocolParametersName) {
    this.protocolParametersName = protocolParametersName;
    return this;
  }

   /**
   * Description
   * @return protocolParametersName
  **/
  @ApiModelProperty(value = "Description")
  public String getProtocolParametersName() {
    return protocolParametersName;
  }

  public void setProtocolParametersName(String protocolParametersName) {
    this.protocolParametersName = protocolParametersName;
  }

  public Study protocolComponentsName(String protocolComponentsName) {
    this.protocolComponentsName = protocolComponentsName;
    return this;
  }

   /**
   * Description
   * @return protocolComponentsName
  **/
  @ApiModelProperty(value = "Description")
  public String getProtocolComponentsName() {
    return protocolComponentsName;
  }

  public void setProtocolComponentsName(String protocolComponentsName) {
    this.protocolComponentsName = protocolComponentsName;
  }

  public Study protocolComponentsType(String protocolComponentsType) {
    this.protocolComponentsType = protocolComponentsType;
    return this;
  }

   /**
   * Description
   * @return protocolComponentsType
  **/
  @ApiModelProperty(value = "Description")
  public String getProtocolComponentsType() {
    return protocolComponentsType;
  }

  public void setProtocolComponentsType(String protocolComponentsType) {
    this.protocolComponentsType = protocolComponentsType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Study study = (Study) o;
    return Objects.equals(this.identifier, study.identifier) &&
        Objects.equals(this.title, study.title) &&
        Objects.equals(this.description, study.description) &&
        Objects.equals(this.designType, study.designType) &&
        Objects.equals(this.assayMeasurementType, study.assayMeasurementType) &&
        Objects.equals(this.assayTechnologyType, study.assayTechnologyType) &&
        Objects.equals(this.assayTechnologyPlatform, study.assayTechnologyPlatform) &&
        Objects.equals(this.accreditationProcedureForTheAssayTechnology, study.accreditationProcedureForTheAssayTechnology) &&
        Objects.equals(this.protocolName, study.protocolName) &&
        Objects.equals(this.protocolType, study.protocolType) &&
        Objects.equals(this.protocolDescription, study.protocolDescription) &&
        Objects.equals(this.protocolURI, study.protocolURI) &&
        Objects.equals(this.protocolVersion, study.protocolVersion) &&
        Objects.equals(this.protocolParametersName, study.protocolParametersName) &&
        Objects.equals(this.protocolComponentsName, study.protocolComponentsName) &&
        Objects.equals(this.protocolComponentsType, study.protocolComponentsType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(identifier, title, description, designType, assayMeasurementType, assayTechnologyType, assayTechnologyPlatform, accreditationProcedureForTheAssayTechnology, protocolName, protocolType, protocolDescription, protocolURI, protocolVersion, protocolParametersName, protocolComponentsName, protocolComponentsType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Study {\n");
    
    sb.append("    identifier: ").append(toIndentedString(identifier)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    designType: ").append(toIndentedString(designType)).append("\n");
    sb.append("    assayMeasurementType: ").append(toIndentedString(assayMeasurementType)).append("\n");
    sb.append("    assayTechnologyType: ").append(toIndentedString(assayTechnologyType)).append("\n");
    sb.append("    assayTechnologyPlatform: ").append(toIndentedString(assayTechnologyPlatform)).append("\n");
    sb.append("    accreditationProcedureForTheAssayTechnology: ").append(toIndentedString(accreditationProcedureForTheAssayTechnology)).append("\n");
    sb.append("    protocolName: ").append(toIndentedString(protocolName)).append("\n");
    sb.append("    protocolType: ").append(toIndentedString(protocolType)).append("\n");
    sb.append("    protocolDescription: ").append(toIndentedString(protocolDescription)).append("\n");
    sb.append("    protocolURI: ").append(toIndentedString(protocolURI)).append("\n");
    sb.append("    protocolVersion: ").append(toIndentedString(protocolVersion)).append("\n");
    sb.append("    protocolParametersName: ").append(toIndentedString(protocolParametersName)).append("\n");
    sb.append("    protocolComponentsName: ").append(toIndentedString(protocolComponentsName)).append("\n");
    sb.append("    protocolComponentsType: ").append(toIndentedString(protocolComponentsType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

